/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.senac.atividade3uc10.view;

import br.com.senac.atividade3uc10.persistencia.Podcast;
import br.com.senac.atividade3uc10.persistencia.PodcastDAO;
import br.com.senac.atividade3uc10.persistencia.Usuario;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author lizz
 */



/** Jframe responsavel pela busca e listagem dos podcasts */

public final class TelaListagem extends javax.swing.JFrame {

    private Usuario usuarioAutenticado;

    public void setUsuarioAutenticado(Usuario usuario) {
        this.usuarioAutenticado = usuario;
    }

    /**
     * Creates new form TelaListagem
     */
    public TelaListagem() {
        initComponents();
        PodcastDAO podcastDAO = new PodcastDAO();
        Usuario Usuario = new Usuario();
        List<Podcast> podcasts = podcastDAO.listar();
        preencheTabela(podcasts);
        ajustarVisibilidadeElementos();
    }

    public void ajustarVisibilidadeElementos() {
        if (TelaLog.isIsAdmin()) {
            // Mostrar elementos específicos para administradores
            btnExcluir.setEnabled(true);
            BtnCadastro.setEnabled(true);
            BtnPesquisar.setEnabled(true);
        } else if (TelaLog.isIsOperador()) {
            btnExcluir.setEnabled(false);
            BtnCadastro.setEnabled(true);
            BtnPesquisar.setEnabled(true);
        } else if (TelaLog.isIsUsuario()) {
            btnExcluir.setEnabled(false);
            BtnCadastro.setEnabled(false);
            BtnPesquisar.setEnabled(true);
        }

    }

    public void preencheTabela(List<Podcast> podcasts) {
        String colunas[] = {"ID", "Produtor", "Nome Do Episodio", "N do episodio", "Duracao", "URL do repo"};
        String dados[][] = new String[podcasts.size()][colunas.length];

        int i = 0;
        for (Podcast r : podcasts) {
            dados[i] = new String[]{
                String.valueOf(r.getId()),
                r.getProdutor(),
                r.getNome_do_episodio(),
                String.valueOf(r.getNumero_do_episodio()),
                r.getDuracao_do_episodio(),
                r.getUrl_do_repositorio()
            };
            i++;
        }
        DefaultTableModel model = new DefaultTableModel(dados, colunas);
        tblPodcasts.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        PesquisaProdutorTxtField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPodcasts = new javax.swing.JTable();
        BtnCadastro = new javax.swing.JButton();
        BtnPesquisar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 1, 36)); // NOI18N
        jLabel1.setText("CENAFLIX");

        jLabel2.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jLabel2.setText("LISTAGEM");

        PesquisaProdutorTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PesquisaProdutorTxtFieldActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jLabel3.setText("Pesquisar podcast por produtor");

        tblPodcasts.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Produtor", "Nome Do Episodio", "N do episodio", "Duracao", "URL do repo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblPodcasts);

        BtnCadastro.setText("Cadastrar");
        BtnCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCadastroActionPerformed(evt);
            }
        });

        BtnPesquisar.setText("Pesquisar");
        BtnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPesquisarActionPerformed(evt);
            }
        });

        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnExcluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BtnCadastro)
                        .addGap(16, 16, 16))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 82, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(BtnPesquisar)
                                        .addGap(173, 173, 173))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(PesquisaProdutorTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(366, 366, 366))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(395, 395, 395))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(440, 440, 440))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(PesquisaProdutorTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnPesquisar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnCadastro)
                    .addComponent(btnExcluir))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPesquisarActionPerformed
        // Obtém o texto inserido no campo de pesquisa
        String produtorPesquisado = PesquisaProdutorTxtField.getText().trim();

        // Verifica se o campo de pesquisa não está vazio
        if (!produtorPesquisado.isEmpty()) {
            PodcastDAO podcastDAO = new PodcastDAO();

            // Realiza a pesquisa pelo produtor
            List<Podcast> podcastsEncontrados = podcastDAO.pesquisarPorProdutor(produtorPesquisado);

            // Atualiza a tabela com os resultados da pesquisa
            preencheTabela(podcastsEncontrados);
        } else {
            // Se o campo de pesquisa estiver vazio, exibe uma mensagem de erro
            JOptionPane.showMessageDialog(this, "Por favor, insira o nome do produtor para pesquisar.", "Campo Vazio", JOptionPane.ERROR_MESSAGE);
        }                        // TODO add your handling code here:
    }//GEN-LAST:event_BtnPesquisarActionPerformed

    private void PesquisaProdutorTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PesquisaProdutorTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PesquisaProdutorTxtFieldActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed

        // Permite a exclusão para Administrador
        String idPodcastString = JOptionPane.showInputDialog(this, "Digite o ID do podcast que deseja excluir:");
        // Verifica se a string não está vazia ou nula antes de tentar converter
        if (idPodcastString != null && !idPodcastString.isEmpty()) {
            int idPodcast = Integer.parseInt(idPodcastString);
            PodcastDAO podcastDAO = new PodcastDAO();
            podcastDAO.excluirPodcastPorId(idPodcast);
            this.repaint();
        } else {
            // Caso o usuário cancele ou não forneça um ID válido
            JOptionPane.showMessageDialog(this, "Nenhum ID fornecido.", "ID Ausente", JOptionPane.WARNING_MESSAGE);
        }

    }//GEN-LAST:event_btnExcluirActionPerformed

    private void BtnCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCadastroActionPerformed

        PodcastDAO podcastDAO = new PodcastDAO();
        FormCadastro FormCadastro = new FormCadastro();
        FormCadastro.setVisible(true);
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnCadastroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaListagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaListagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaListagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaListagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaListagem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCadastro;
    private javax.swing.JButton BtnPesquisar;
    private javax.swing.JTextField PesquisaProdutorTxtField;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblPodcasts;
    // End of variables declaration//GEN-END:variables
}
